name: Release FVTT Module

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      # 1. 태그에서 버전 추출
      - name: Set version from tag
        id: get_version
        run: |
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # 2. module.json 갱신 (version, download, manifest, id만)
      - name: Update module.json
        run: |
          node <<'EOF'
          const fs = require('fs');
          const { execSync } = require('child_process');
          const version = process.env.VERSION;
          const path = 'module.json';

          const json = JSON.parse(fs.readFileSync(path,'utf8'));

          // version 갱신
          json.version = version;

          // download URL 갱신
          json.download = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/download/v${version}/SR5ko.zip`;

          // manifest URL 갱신
          json.manifest = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/latest/download/module.json`;

          // id 유지/추가
          if (!json.id) json.id = "shadowrun5eko";

          fs.writeFileSync(path, JSON.stringify(json, null, 2), 'utf8');

          // 저장소 커밋
          execSync('git config user.name "github-actions"');
          execSync('git config user.email "github-actions@github.com"');
          execSync(`git add ${path}`);
          execSync(`git commit -m "Auto update module.json for v${version}"`);
          execSync('git push');
          EOF
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      # 3. ZIP 빌드
      - name: Build module ZIP
        run: |
          zip -r SR5ko.zip . -x ".git/*" ".github/*"

      # 4. Release 생성 및 파일 업로드
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SR5ko.zip
            module.json
