name: Release FVTT Module

# 태그 푸시 이벤트에서만 실행
on:
  push:
    tags:
      - 'v*.*.*'   # 예: v1.2.4

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      # GitHub Secrets에 등록한 PAT 사용
      GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
    steps:
      # 소스코드 체크아웃
      - uses: actions/checkout@v4

      # 태그에서 버전 추출
      - name: Set version from tag
        id: get_version
        run: |
          echo "TAG REF: $GITHUB_REF"
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      # module.json 버전과 download URL 갱신
      - name: Update module.json
        run: |
          node <<'EOF'
          const fs = require('fs');
          const version = process.env.VERSION;
          const path = 'module.json';

          const json = JSON.parse(fs.readFileSync(path,'utf8'));
          console.log("Old version:", json.version);

          json.version = version;
          json.download = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/download/v${version}/SR5ko.zip`;
          json.manifest = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/latest/download/module.json`;

          fs.writeFileSync(path, JSON.stringify(json, null, 2), 'utf8');
          console.log("New version:", json.version);
          EOF
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      # ZIP 빌드 (ko.json 포함)
      - name: Build module ZIP
        run: |
          zip -r SR5ko.zip . -x ".git/*" ".github/*"

      # Release 생성 및 파일 업로드
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SR5ko.zip
            module.json
