name: Release FVTT Module

on:
  push:
    tags:
      - '*.*.*'  # v 접두사 없이 숫자.숫자.숫자 형식의 태그 푸시 시 실행

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
    steps:
      # 1. 저장소 체크아웃
      - uses: actions/checkout@v4

      # 2. 태그에서 version 추출
      - name: Set version from tag
        id: get_version
        run: |
          echo "GITHUB_REF=$GITHUB_REF"
          if [[ "$GITHUB_REF" =~ refs/tags/([0-9]+\.[0-9]+\.[0-9]+) ]]; then
            VERSION="${BASH_REMATCH[1]}"
          else
            echo "::error ::Invalid tag format. Use X.Y.Z"
            exit 1
          fi
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Extracted version: $VERSION"

      # 3. Release용 module.json 준비 및 갱신
      - name: Prepare module.json for Release
        run: |
          mkdir release
          cp module.json release/module.json
          cd release
          node <<'EOF'
          const fs = require('fs');
          const version = process.env.VERSION;

          if (!version) {
            console.error("VERSION is undefined. Exiting.");
            process.exit(1);
          }

          const path = 'module.json';
          const json = JSON.parse(fs.readFileSync(path,'utf8'));

          // version, download, manifest, id 갱신
          json.version = version;
          json.download = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/download/${version}/SR5ko.zip`;
          json.manifest = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/latest/download/module.json`;
          if (!json.id) json.id = "shadowrun5eko";

          fs.writeFileSync(path, JSON.stringify(json, null, 2), 'utf8');
          EOF
          cd ..
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      # 4. ZIP 빌드
      - name: Build module ZIP
        run: |
          zip -r SR5ko.zip . -x ".git/*" ".github/*"

      # 5. Release 생성 및 파일 업로드
      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SR5ko.zip
            release/module.json
