name: Release FVTT Module

on:
  push:
    tags:
      - 'v*.*.*'   # 예: v1.6.1 같은 태그를 push하면 실행됨

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update module.json (safe JSON edit)
        run: |
          node <<'EOF'
          const fs = require('fs');
          const path = 'module.json';
          const version = process.env.VERSION;

          const json = JSON.parse(fs.readFileSync(path, 'utf8'));
          json.version = version;
          json.download = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/download/v${version}/SR5ko.zip`;

          fs.writeFileSync(path, JSON.stringify(json, null, 2), 'utf8');
          EOF
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Zip module
        run: |
          zip -r SR5ko.zip . -x ".git/*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SR5ko.zip
            module.json

  env:
    GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
