name: Release FVTT Module

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write
  packages: write
  actions: write

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - name: Set version from tag
        id: get_version
        run: |
          echo "TAG REF: $GITHUB_REF"
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update module.json
        run: |
          node <<'EOF'
          const fs = require('fs');
          const version = process.env.VERSION;
          const path = 'module.json';

          const json = JSON.parse(fs.readFileSync(path,'utf8'));
          console.log("Old version:", json.version);

          json.version = version;
          json.download = `https://github.com/${process.env.GITHUB_REPOSITORY}/releases/download/v${version}/SR5ko.zip`;

          fs.writeFileSync(path, JSON.stringify(json, null, 2), 'utf8');
          console.log("New version:", json.version);
          EOF
        env:
          VERSION: ${{ steps.get_version.outputs.version }}
          GITHUB_REPOSITORY: ${{ github.repository }}

      - name: Zip module
        run: |
          zip -r SR5ko.zip . -x ".git/*" ".github/*"

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            SR5ko.zip
            module.json
